/* 
 * FEIMusic API
 *
 * Api que nos permite administrar la aplicacion de musica FEIMusic
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = FEiMusic.Client.SwaggerDateConverter;

namespace FEiMusic.Model
{
    /// <summary>
    /// AlbumResponse
    /// </summary>
    [DataContract]
        public partial class AlbumResponse :  IEquatable<AlbumResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlbumResponse" /> class.
        /// </summary>
        /// <param name="idAlbum">idAlbum.</param>
        /// <param name="nombreAlbum">nombreAlbum.</param>
        public AlbumResponse(string idAlbum = default(string), string nombreAlbum = default(string))
        {
            this.IdAlbum = idAlbum;
            this.NombreAlbum = nombreAlbum;
        }
        
        /// <summary>
        /// Gets or Sets IdAlbum
        /// </summary>
        [DataMember(Name="idAlbum", EmitDefaultValue=false)]
        public string IdAlbum { get; set; }

        /// <summary>
        /// Gets or Sets NombreAlbum
        /// </summary>
        [DataMember(Name="nombreAlbum", EmitDefaultValue=false)]
        public string NombreAlbum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlbumResponse {\n");
            sb.Append("  IdAlbum: ").Append(IdAlbum).Append("\n");
            sb.Append("  NombreAlbum: ").Append(NombreAlbum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlbumResponse);
        }

        /// <summary>
        /// Returns true if AlbumResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AlbumResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlbumResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IdAlbum == input.IdAlbum ||
                    (this.IdAlbum != null &&
                    this.IdAlbum.Equals(input.IdAlbum))
                ) && 
                (
                    this.NombreAlbum == input.NombreAlbum ||
                    (this.NombreAlbum != null &&
                    this.NombreAlbum.Equals(input.NombreAlbum))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdAlbum != null)
                    hashCode = hashCode * 59 + this.IdAlbum.GetHashCode();
                if (this.NombreAlbum != null)
                    hashCode = hashCode * 59 + this.NombreAlbum.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
