/* 
 * FEIMusic API
 *
 * Api que nos permite administrar la aplicacion de musica FEIMusic
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = FEiMusic.Client.SwaggerDateConverter;

namespace FEiMusic.Model
{
    /// <summary>
    /// Cancion
    /// </summary>
    [DataContract]
        public partial class Cancion :  IEquatable<Cancion>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Cancion" /> class.
        /// </summary>
        /// <param name="idCancion">idCancion.</param>
        /// <param name="nombreCancion">nombreCancion.</param>
        /// <param name="letra">letra.</param>
        /// <param name="imagenCancion">imagenCancion.</param>
        /// <param name="track">track.</param>
        /// <param name="idAlbum">idAlbum.</param>
        /// <param name="idGenero">idGenero.</param>
        public Cancion(string idCancion = default(string), string nombreCancion = default(string), string letra = default(string), string imagenCancion = default(string), string track = default(string), string idAlbum = default(string), string idGenero = default(string))
        {
            this.IdCancion = idCancion;
            this.NombreCancion = nombreCancion;
            this.Letra = letra;
            this.ImagenCancion = imagenCancion;
            this.Track = track;
            this.IdAlbum = idAlbum;
            this.IdGenero = idGenero;
        }
        
        /// <summary>
        /// Gets or Sets IdCancion
        /// </summary>
        [DataMember(Name="idCancion", EmitDefaultValue=false)]
        public string IdCancion { get; set; }

        /// <summary>
        /// Gets or Sets NombreCancion
        /// </summary>
        [DataMember(Name="nombreCancion", EmitDefaultValue=false)]
        public string NombreCancion { get; set; }

        /// <summary>
        /// Gets or Sets Letra
        /// </summary>
        [DataMember(Name="letra", EmitDefaultValue=false)]
        public string Letra { get; set; }

        /// <summary>
        /// Gets or Sets ImagenCancion
        /// </summary>
        [DataMember(Name="imagenCancion", EmitDefaultValue=false)]
        public string ImagenCancion { get; set; }

        /// <summary>
        /// Gets or Sets Track
        /// </summary>
        [DataMember(Name="track", EmitDefaultValue=false)]
        public string Track { get; set; }

        /// <summary>
        /// Gets or Sets IdAlbum
        /// </summary>
        [DataMember(Name="idAlbum", EmitDefaultValue=false)]
        public string IdAlbum { get; set; }

        /// <summary>
        /// Gets or Sets IdGenero
        /// </summary>
        [DataMember(Name="idGenero", EmitDefaultValue=false)]
        public string IdGenero { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Cancion {\n");
            sb.Append("  IdCancion: ").Append(IdCancion).Append("\n");
            sb.Append("  NombreCancion: ").Append(NombreCancion).Append("\n");
            sb.Append("  Letra: ").Append(Letra).Append("\n");
            sb.Append("  ImagenCancion: ").Append(ImagenCancion).Append("\n");
            sb.Append("  Track: ").Append(Track).Append("\n");
            sb.Append("  IdAlbum: ").Append(IdAlbum).Append("\n");
            sb.Append("  IdGenero: ").Append(IdGenero).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Cancion);
        }

        /// <summary>
        /// Returns true if Cancion instances are equal
        /// </summary>
        /// <param name="input">Instance of Cancion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Cancion input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IdCancion == input.IdCancion ||
                    (this.IdCancion != null &&
                    this.IdCancion.Equals(input.IdCancion))
                ) && 
                (
                    this.NombreCancion == input.NombreCancion ||
                    (this.NombreCancion != null &&
                    this.NombreCancion.Equals(input.NombreCancion))
                ) && 
                (
                    this.Letra == input.Letra ||
                    (this.Letra != null &&
                    this.Letra.Equals(input.Letra))
                ) && 
                (
                    this.ImagenCancion == input.ImagenCancion ||
                    (this.ImagenCancion != null &&
                    this.ImagenCancion.Equals(input.ImagenCancion))
                ) && 
                (
                    this.Track == input.Track ||
                    (this.Track != null &&
                    this.Track.Equals(input.Track))
                ) && 
                (
                    this.IdAlbum == input.IdAlbum ||
                    (this.IdAlbum != null &&
                    this.IdAlbum.Equals(input.IdAlbum))
                ) && 
                (
                    this.IdGenero == input.IdGenero ||
                    (this.IdGenero != null &&
                    this.IdGenero.Equals(input.IdGenero))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdCancion != null)
                    hashCode = hashCode * 59 + this.IdCancion.GetHashCode();
                if (this.NombreCancion != null)
                    hashCode = hashCode * 59 + this.NombreCancion.GetHashCode();
                if (this.Letra != null)
                    hashCode = hashCode * 59 + this.Letra.GetHashCode();
                if (this.ImagenCancion != null)
                    hashCode = hashCode * 59 + this.ImagenCancion.GetHashCode();
                if (this.Track != null)
                    hashCode = hashCode * 59 + this.Track.GetHashCode();
                if (this.IdAlbum != null)
                    hashCode = hashCode * 59 + this.IdAlbum.GetHashCode();
                if (this.IdGenero != null)
                    hashCode = hashCode * 59 + this.IdGenero.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
