/* 
 * FEIMusic API
 *
 * Api que nos permite administrar la aplicacion de musica FEIMusic
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = FEiMusic.Client.SwaggerDateConverter;

namespace FEiMusic.Model
{
    /// <summary>
    /// ListaReproduccionResponse
    /// </summary>
    [DataContract]
        public partial class ListaReproduccionResponse :  IEquatable<ListaReproduccionResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListaReproduccionResponse" /> class.
        /// </summary>
        /// <param name="idListaReproduccion">idListaReproduccion.</param>
        /// <param name="nombre">nombre.</param>
        public ListaReproduccionResponse(string idListaReproduccion = default(string), string nombre = default(string))
        {
            this.IdListaReproduccion = idListaReproduccion;
            this.Nombre = nombre;
        }
        
        /// <summary>
        /// Gets or Sets IdListaReproduccion
        /// </summary>
        [DataMember(Name="idListaReproduccion", EmitDefaultValue=false)]
        public string IdListaReproduccion { get; set; }

        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [DataMember(Name="nombre", EmitDefaultValue=false)]
        public string Nombre { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListaReproduccionResponse {\n");
            sb.Append("  IdListaReproduccion: ").Append(IdListaReproduccion).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListaReproduccionResponse);
        }

        /// <summary>
        /// Returns true if ListaReproduccionResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ListaReproduccionResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListaReproduccionResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IdListaReproduccion == input.IdListaReproduccion ||
                    (this.IdListaReproduccion != null &&
                    this.IdListaReproduccion.Equals(input.IdListaReproduccion))
                ) && 
                (
                    this.Nombre == input.Nombre ||
                    (this.Nombre != null &&
                    this.Nombre.Equals(input.Nombre))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdListaReproduccion != null)
                    hashCode = hashCode * 59 + this.IdListaReproduccion.GetHashCode();
                if (this.Nombre != null)
                    hashCode = hashCode * 59 + this.Nombre.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
